

################################## 
### Registry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      component: docker-registry
  template:
    metadata:
      labels:
        component: docker-registry 
    spec:
      volumes:
        - name: docker-registry-database-volume
          persistentVolumeClaim:
            claimName: docker-registry-pvc
        - name: docker-certs-volume
          secret:
            secretName: docker-registry-certs-secret
        - name: docker-auth-volume
          secret:
            secretName: docker-registry-auth-secret
      containers:
        - name: docker-registry
          image: registry:latest
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
            # - name: REGISTRY_HTTP_TLS_CERTIFICATE
            #   value: "/certs/tls.crt"
            # - name: REGISTRY_HTTP_TLS_KEY
            #   value: "/certs/tls.key"
          volumeMounts:
          - name: docker-registry-database-volume
            mountPath: "/var/lib/registry"
          # - name: docker-certs-volume
          #   mountPath: "/certs"
          - name: docker-auth-volume
            mountPath: "/auth"
---

################################## 
### Service

apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: docker-registry
spec:
  type: NodePort
  selector:
    component: docker-registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: __DOCKER_PORT__
---
