##################################
### Certificate issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-__NAMESPACE__-issuer
  namespace: __NAMESPACE__
spec:
  acme:
    # The ACME server URL
    # production:
    server: https://acme-v02.api.letsencrypt.org/directory

    # staging:
    #server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email address used for ACME registration
    email: __MAIL__
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-__NAMESPACE__-production
    # Enable the HTTP-01 challenge provider
    solvers:
      - selector: {}
        http01:
          ingress:
            ingressClassName: traefik
---

##################################
### Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-__NAMESPACE__
  namespace: __NAMESPACE__
spec:
  secretName: tls-__NAMESPACE__
  commonName: __DOMAIN__
  issuerRef:
    name: letsencrypt-__NAMESPACE__-issuer
    kind: Issuer
  dnsNames:
  - __DOMAIN__
---
